
project_id = "avishkar-academy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[functions.process-google-pay]
verify_jwt = false

[functions.send-enquiry]
verify_jwt = false
