
project_id = "iflffrqsbsklyhfuskxt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true

[inbucket]
enabled = true

[analytics]
enabled = false
