
project_id = "iflffrqsbsklyhfuskxt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
# Disable email confirmations for faster testing
email_confirm_required = false

[inbucket]
enabled = true

[analytics]
enabled = false

[[storage.buckets]]
name = "images"
public = true

[[storage.buckets]]
name = "materials"
public = true
